# Generated by Django 2.1.2 on 2018-10-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE TABLE IF NOT EXISTS ov.companies (cin BIGINT NOT NULL PRIMARY KEY, name character varying, br_section character varying, address_line character varying NOT NULL, last_update timestamp without time zone NOT NULL, created_at timestamp without time zone NOT NULL, updated_at timestamp without time zone NOT NULL);'),
        migrations.RunSQL([('INSERT INTO ov.companies (cin, name, br_section, address_line, last_update, created_at, updated_at) SELECT a.cin, a.corporate_body_name, a.br_section, CONCAT(a.street, (%s), a.postal_code, a.city), a.updated_at, now(), now() FROM ( SELECT s.*, RANK() OVER debilko AS maxrank FROM ov.or_podanie_issues AS s WINDOW debilko AS (PARTITION BY cin ORDER BY updated_at DESC) ) AS a WHERE NOT EXISTS(SELECT cin FROM ov.companies c WHERE c.cin = a.cin) and a.cin IS NOT NULL and a.maxrank = 1;', [', '])]),
        migrations.RunSQL([('INSERT INTO ov.companies (cin, name, br_section, address_line, last_update, created_at, updated_at) SELECT a.cin, a.corporate_body_name, a.br_section, CONCAT(a.street, (%s), a.postal_code, a.city), a.updated_at, now(), now() FROM ( SELECT s.*, RANK() OVER debilko AS maxrank FROM ov.likvidator_issues AS s WINDOW debilko AS (PARTITION BY cin ORDER BY updated_at DESC) ) AS a WHERE NOT EXISTS(SELECT cin FROM ov.companies c WHERE c.cin = a.cin) and a.cin IS NOT NULL and a.maxrank = 1;', [', '])]),
        migrations.RunSQL([('INSERT INTO ov.companies (cin, name, br_section, address_line, last_update, created_at, updated_at) SELECT a.cin, a.corporate_body_name, (%s), CONCAT(a.street, (%s), a.postal_code, a.city), a.updated_at, now(), now() FROM ( SELECT s.*, RANK() OVER debilko AS maxrank FROM ov.konkurz_vyrovnanie_issues AS s WINDOW debilko AS (PARTITION BY cin ORDER BY updated_at DESC) ) AS a WHERE NOT EXISTS(SELECT cin FROM ov.companies c WHERE c.cin = a.cin) and a.cin IS NOT NULL and a.maxrank = 1;', [', ', ''],)]),
        migrations.RunSQL([('INSERT INTO ov.companies (cin, name, br_section, address_line, last_update, created_at, updated_at) SELECT a.cin, a.corporate_body_name, a.br_section, CONCAT(a.street, (%s), a.postal_code, a.city), a.updated_at, now(), now() FROM ( SELECT s.*, RANK() OVER debilko AS maxrank FROM ov.znizenie_imania_issues AS s WINDOW debilko AS (PARTITION BY cin ORDER BY updated_at DESC) ) AS a WHERE NOT EXISTS(SELECT cin FROM ov.companies c WHERE c.cin = a.cin) and a.cin IS NOT NULL and a.maxrank = 1;', [', '])]),
        migrations.RunSQL([('INSERT INTO ov.companies (cin, name, br_section, address_line, last_update, created_at, updated_at) SELECT a.cin, a.corporate_body_name, (%s), CONCAT(a.street, (%s), a.postal_code, a.city), a.updated_at, now(), now() FROM ( SELECT s.*, RANK() OVER debilko AS maxrank FROM ov.konkurz_restrukturalizacia_actors AS s WINDOW debilko AS (PARTITION BY cin ORDER BY updated_at DESC) ) AS a WHERE NOT EXISTS(SELECT cin FROM ov.companies c WHERE c.cin = a.cin) and a.cin IS NOT NULL and a.maxrank = 1;', [', ', ''])]),    
    ]
